# Ref: https://pkg.go.dev/github.com/spf13/viper

# API config
[api]
port = "8080"

# Database config
[database]
host = "localhost"
port = "5432"
user = "user_tasks"
password = "5995"
name = "api_tasks"